Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ./cbpm/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer-cbpm:7050

    - &ManufacturerOrg
        Name: ManufacturerOrg
        ID: ManufacturerMSP
        MSPDir: ./manufacturer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ManufacturerMSP.peer')"
        AnchorPeers:
            - Host: peer1-manufacturer
              Port: 7051


    - &SupplierOrg
        Name: SupplierOrg
        ID: SupplierMSP
        MSPDir: ./supplier/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.peer', 'SupplierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('SupplierMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('SupplierMSP.peer')"
        AnchorPeers:
            - Host: peer1-supplier
              Port: 7051

    - &CarrierOrg
        Name: CarrierOrg
        ID: CarrierMSP
        MSPDir: ./carrier/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CarrierMSP.admin', 'CarrierMSP.peer', 'CarrierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CarrierMSP.admin', 'CarrierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CarrierMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CarrierMSP.peer')"

        AnchorPeers:
            - Host: peer1-carrier
              Port: 7051

    - &MiddlemanOrg
        Name: MiddlemanOrg
        ID: MiddlemanMSP

        MSPDir: ./middleman/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin', 'MiddlemanMSP.peer', 'MiddlemanMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin', 'MiddlemanMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('MiddlemanMSP.peer')"

        AnchorPeers:
            - Host: peer1-middleman
              Port: 7051
Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false  
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer-cbpm:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
Profiles:
    CBPMOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: 
                <<: *OrdererCapabilities
        Consortiums:
            CBPMConsortium:
                Organizations:
                    - *SupplierOrg
                    - *CarrierOrg
                    - *ManufacturerOrg
                    - *MiddlemanOrg
            SCConsortium:
                Organizations:
                    - *SupplierOrg
                    - *CarrierOrg
    SCChannel:
        <<: *ChannelDefaults
        Consortium: SCConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *SupplierOrg
                - *CarrierOrg
            Capabilities: *ApplicationCapabilities