Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ./cbpm/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

        OrdererEndpoints:
            - orderer-cbpm:7050

    - &ManufacturerOrg
        Name: ManufacturerOrg
        ID: ManufacturerMSP
        MSPDir: ./manufacturer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ManufacturerMSP.peer')"
        AnchorPeers:
            - Host: peer1-manufacturer
              Port: 7051


    - &SupplierOrg
        Name: SupplierOrg
        ID: SupplierMSP
        MSPDir: ./supplier/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.peer', 'SupplierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('SupplierMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('SupplierMSP.peer')"
        AnchorPeers:
            - Host: peer1-supplier
              Port: 7051

    - &CarrierOrg
        Name: CarrierOrg
        ID: CarrierMSP
        MSPDir: ./carrier/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CarrierMSP.admin', 'CarrierMSP.peer', 'CarrierMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CarrierMSP.admin', 'CarrierMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CarrierMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CarrierMSP.peer')"

        AnchorPeers:
            - Host: peer1-carrier
              Port: 7051

    - &MiddlemanOrg
        Name: MiddlemanOrg
        ID: MiddlemanMSP

        MSPDir: ./middleman/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin', 'MiddlemanMSP.peer', 'MiddlemanMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin', 'MiddlemanMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('MiddlemanMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('MiddlemanMSP.peer')"

        AnchorPeers:
            - Host: peer1-middleman
              Port: 7051
Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false  
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer-cbpm:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    
    EtcdRaft:
        Consenters:
            - Host: orderer-cbpm
              Port: 7050
              ClientTLSCert: ./cbpm/orderer/tls/signcerts/cert.pem
              ServerTLSCert: ./cbpm/orderer/tls/signcerts/cert.pem
            - Host: orderer2-cbpm
              Port: 7050
              ClientTLSCert: ./cbpm/orderer2/tls/signcerts/cert.pem
              ServerTLSCert: ./cbpm/orderer2/tls/signcerts/cert.pem
            - Host: orderer3-cbpm
              Port: 7050
              ClientTLSCert: ./cbpm/orderer3/tls/signcerts/cert.pem
              ServerTLSCert: ./cbpm/orderer3/tls/signcerts/cert.pem
            - Host: orderer4-cbpm
              Port: 7050
              ClientTLSCert: ./cbpm/orderer4/tls/signcerts/cert.pem
              ServerTLSCert: ./cbpm/orderer4/tls/signcerts/cert.pem
            - Host: orderer5-cbpm
              Port: 7050
              ClientTLSCert: ./cbpm/orderer5/tls/signcerts/cert.pem
              ServerTLSCert: ./cbpm/orderer5/tls/signcerts/cert.pem
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
Profiles:
    CBPMOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities: 
                <<: *OrdererCapabilities
        Consortiums:
            CBPMConsortium:
                Organizations:
                    - *SupplierOrg
                    - *CarrierOrg
                    - *ManufacturerOrg
                    - *MiddlemanOrg
            # SCConsortium:
            #     Organizations:
            #         - *SupplierOrg
            #         - *CarrierOrg
            # MaMiConsortium:
            #     Organizations:
            #         - *ManufacturerOrg
            #         - *MiddlemanOrg
            # MiSConsortium:
            #     Organizations:
            #         - *MiddlemanOrg
            #         - *SupplierOrg   
            # MiCConsortium:
            #     Organizations:
            #         - *MiddlemanOrg
            #         - *CarrierOrg 
            # CMaConsortium:
            #     Organizations:
            #         - *CarrierOrg
            #         - *ManufacturerOrg
    CBPMChannel:
        <<: *ChannelDefaults
        Consortium: CBPMConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ManufacturerOrg
                - *MiddlemanOrg
                - *SupplierOrg
                - *CarrierOrg
            Capabilities: *ApplicationCapabilities

    
    CBPMMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer-cbpm
                  Port: 7050
                  ClientTLSCert: ./cbpm/orderer/tls/signcerts/cert.pem
                  ServerTLSCert: ./cbpm/orderer/tls/signcerts/cert.pem
                - Host: orderer2-cbpm
                  Port: 7050
                  ClientTLSCert: ./cbpm/orderer2/tls/signcerts/cert.pem
                  ServerTLSCert: ./cbpm/orderer2/tls/signcerts/cert.pem
                - Host: orderer3-cbpm
                  Port: 7050
                  ClientTLSCert: ./cbpm/orderer3/tls/signcerts/cert.pem
                  ServerTLSCert: ./cbpm/orderer3/tls/signcerts/cert.pem
                - Host: orderer4-cbpm
                  Port: 7050
                  ClientTLSCert: ./cbpm/orderer4/tls/signcerts/cert.pem
                  ServerTLSCert: ./cbpm/orderer4/tls/signcerts/cert.pem
                - Host: orderer5-cbpm
                  Port: 7050
                  ClientTLSCert: ./cbpm/orderer5/tls/signcerts/cert.pem
                  ServerTLSCert: ./cbpm/orderer5/tls/signcerts/cert.pem
            Addresses:
                - orderer-cbpm:7050
                - orderer2-cbpm:7050
                - orderer3-cbpm:7050
                - orderer4-cbpm:7050
                - orderer5-cbpm:7050
            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            CBPMConsortium:
                Organizations:
                - *ManufacturerOrg
                - *MiddlemanOrg
                - *SupplierOrg
                - *CarrierOrg




    # SCChannel:
    #     <<: *ChannelDefaults
    #     Consortium: SCConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *SupplierOrg
    #             - *CarrierOrg
    #         Capabilities: *ApplicationCapabilities

    # MaMiChannel:
    #     <<: *ChannelDefaults
    #     Consortium: MaMiConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *ManufacturerOrg
    #             - *MiddlemanOrg
    #         Capabilities: *ApplicationCapabilities
    # MiSChannel:
    #     <<: *ChannelDefaults
    #     Consortium: MiSConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *MiddlemanOrg
    #             - *SupplierOrg
    #         Capabilities: *ApplicationCapabilities
    # MiCChannel:
    #     <<: *ChannelDefaults
    #     Consortium: MiCConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *MiddlemanOrg
    #             - *CarrierOrg
    #         Capabilities: *ApplicationCapabilities
    # CMaChannel:
    #     <<: *ChannelDefaults
    #     Consortium: CMaConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *CarrierOrg
    #             - *ManufacturerOrg
    #         Capabilities: *ApplicationCapabilities
