version: "3.7"

networks:
  cbpm-network:
services:
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment: 
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - cbpm-network

   # couchdb2:
   #  container_name: couchdb
   #  image: hyperledger/fabric-couchdb
   #  environment: 
   #   - COUCHDB_USER=admin
   #   - COUCHDB_PASSWORD=123456
   #  # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
   #  # for example map it to utilize Fauxton User Interface in dev environments.
   #  ports:
   #    - "6984:5984"
   #  networks:
   #    - cbpm-network

   # couchdb3:
   #  container_name: couchdb
   #  image: hyperledger/fabric-couchdb
   #  environment: 
   #   - COUCHDB_USER=admin
   #   - COUCHDB_PASSWORD=123456
   #  # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
   #  # for example map it to utilize Fauxton User Interface in dev environments.
   #  ports:
   #    - "7984:5984"
   #  networks:
   #    - cbpm-network

   # couchdb4:
   #  container_name: couchdb
   #  image: hyperledger/fabric-couchdb
   #  environment: 
   #   - COUCHDB_USER=admin
   #   - COUCHDB_PASSWORD=123456
   #  # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
   #  # for example map it to utilize Fauxton User Interface in dev environments.
   #  ports:
   #    - "8984:5984"
   #  networks:
   #    - cbpm-network

  ca-tls:
    container_name: ca
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/tls
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7052
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7052:7052

  cbpm-ca:
    container_name: cbpm-ca
    image: hyperledger/fabric-ca
    command: /bin/sh -c 'fabric-ca-server start -d -b cbpm-ca-admin:cbpm-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/cbpm
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=cbpm
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7053
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7053:7053

  manufacturer-ca:
    container_name: manufacturer-ca
    image: hyperledger/fabric-ca
    command: /bin/sh -c 'fabric-ca-server start -d -b manufacturer-ca-admin:manufacturer-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/manufacturer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=manufacturer
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7054:7054

  supplier-ca:
    container_name: supplier-ca
    image: hyperledger/fabric-ca
    command: /bin/sh -c 'fabric-ca-server start -d -b supplier-ca-admin:supplier-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/supplier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=supplier
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7055
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7055:7055

  carrier-ca:
    container_name: carrier-ca
    image: hyperledger/fabric-ca
    command: /bin/sh -c 'fabric-ca-server start -d -b carrier-ca-admin:carrier-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/carrier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=carrier
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7056
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7056:7056

  middleman-ca:
    container_name: middleman-ca
    image: hyperledger/fabric-ca
    command: /bin/sh -c 'fabric-ca-server start -d -b middleman-ca-admin:middleman-adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/ca/middleman
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=middleman
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_PORT=7057
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./:/ca
    networks:
      - cbpm-network
    ports:
      - 7057:7057

  orderer-cbpm:
    container_name: orderer-cbpm
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_HOME=/tmp/hyperledger/cbpm
      - ORDERER_HOST=orderer-cbpm
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/cbpm/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/cbpm/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/cbpm/orderer/tls/keystore/key.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/cbpm/orderer/tls/tlscacerts/tls-0-0-0-0-7052.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
    volumes:
      - ./cbpm:/tmp/hyperledger/cbpm
      - ./channel-artifacts/genesis.block:/tmp/hyperledger/genesis.block
    networks:
      - cbpm-network
    ports:
      - 7050:7050

  peer1-manufacturer:
    container_name: peer1-manufacturer
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer1-manufacturer
      - CORE_PEER_ADDRESS=peer1-manufacturer:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/manufacturer/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/manufacturer/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/manufacturer/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/manufacturer/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-manufacturer:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/manufacturer/peer1
    volumes:
      - /var/run:/host/var/run
      - ./manufacturer/peer1:/tmp/hyperledger/manufacturer/peer1
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8051:7051

  peer2-manufacturer:
    container_name: peer2-manufacturer
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer2-manufacturer
      - CORE_PEER_ADDRESS=peer2-manufacturer:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/manufacturer/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/manufacturer/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/manufacturer/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/manufacturer/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-manufacturer:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/manufacturer/peer2
    volumes:
      - /var/run:/host/var/run
      - ./manufacturer/peer2:/tmp/hyperledger/manufacturer/peer2
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8151:7051


  peer1-supplier:
    container_name: peer1-supplier
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer1-supplier
      - CORE_PEER_ADDRESS=peer1-supplier:7051
      - CORE_PEER_LOCALMSPID=SupplierMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/supplier/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/supplier/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/supplier/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/supplier/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-supplier:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/supplier/peer1
    volumes:
      - /var/run:/host/var/run
      - ./supplier/peer1:/tmp/hyperledger/supplier/peer1
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8251:7051

  peer2-supplier:
    container_name: peer2-supplier
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer2-supplier
      - CORE_PEER_ADDRESS=peer2-supplier:7051
      - CORE_PEER_LOCALMSPID=SupplierMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/supplier/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/supplier/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/supplier/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/supplier/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-supplier:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/supplier/peer2
    volumes:
      - /var/run:/host/var/run
      - ./supplier/peer2:/tmp/hyperledger/supplier/peer2
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8351:7051

  peer1-carrier:
    container_name: peer1-carrier
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer1-carrier
      - CORE_PEER_ADDRESS=peer1-carrier:7051
      - CORE_PEER_LOCALMSPID=CarrierMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/carrier/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/carrier/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/carrier/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/carrier/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-carrier:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/carrier/peer1
    volumes:
      - /var/run:/host/var/run
      - ./carrier/peer1:/tmp/hyperledger/carrier/peer1
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8451:7051

  peer2-carrier:
    container_name: peer2-carrier
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer2-carrier
      - CORE_PEER_ADDRESS=peer2-carrier:7051
      - CORE_PEER_LOCALMSPID=CarrierMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/carrier/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/carrier/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/carrier/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/carrier/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-carrier:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/carrier/peer2
    volumes:
      - /var/run:/host/var/run
      - ./carrier/peer2:/tmp/hyperledger/carrier/peer2
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8551:7051

  peer1-middleman:
    container_name: peer1-middleman
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer1-middleman
      - CORE_PEER_ADDRESS=peer1-middleman:7051
      - CORE_PEER_LOCALMSPID=MiddlemanMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/middleman/peer1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/middleman/peer1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/middleman/peer1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/middleman/peer1/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-middleman:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hperledger/middleman/peer1
    volumes:
      - /var/run:/host/var/run
      - ./middleman/peer1:/tmp/hyperledger/middleman/peer1
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8651:7051

  peer2-middleman:
    container_name: peer2-middleman
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer2-middleman
      - CORE_PEER_ADDRESS=peer2-middleman:7051
      - CORE_PEER_LOCALMSPID=MiddlemanMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/middleman/peer2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_cbpm-network
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/middleman/peer2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/middleman/peer2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/middleman/peer2/tls/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-middleman:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    working_dir: /tmp/hyperledger/middleman/peer2
    volumes:
      - /var/run:/host/var/run
      - ./middleman/peer2:/tmp/hyperledger/middleman/peer2
    networks:
      - cbpm-network
    depends_on:
      - couchdb1
    ports:
      - 8751:7051

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/tmp/hyperledger/fabric/chaincode/go
      - GO111MODULE=auto
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_TLS_ENABLED=true
    working_dir: /tmp/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/tmp/hyperledger/fabric/channel-artifacts
      - ./manufacturer:/tmp/hyperledger/fabric/peer/manufacturer
      - ./supplier:/tmp/hyperledger/fabric/peer/supplier
      - ./carrier:/tmp/hyperledger/fabric/peer/carrier
      - ./middleman:/tmp/hyperledger/fabric/peer/middleman
      - ./cbpm:/tmp/hyperledger/fabric/peer/cbpm
      - ./scripts:/tmp/hyperledger/fabric/peer/scripts
      - ../chaincode/go:/tmp/hyperledger/fabric/chaincode/go/src
      - ../chaincode/java:/tmp/hyperledger/fabric/chaincode/java
    networks:
      - cbpm-network
    depends_on:
      - peer1-manufacturer
      - peer2-manufacturer
      - peer1-carrier
      - peer2-carrier
      - peer1-supplier
      - peer2-supplier
      - peer1-middleman
      - peer2-middleman

