server:
  port: 8080
#linux环境
spring:
  application:
    name: backend

backend:
  # 网络配置文件路径
  networkConfigPath: /home/steve/homework/cBPM-blockchain-system/backend/connection-linux.json
  #network path
  networkPath: /home/steve/homework/cBPM-blockchain-system/network/
  #logPath
  logPackagePath: /home/steve/homework/cBPM-blockchain-system/backend/src/main/logs/