server:
  port: 8080
#linux环境
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://172.19.241.74:3306/blockChain
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

backend:
  # 网络配置文件路径
  networkConfigPath: /home/steve/homework/cBPM-blockchain-system/backend/connection-linux.json
  #network path
  networkPath: /home/steve/homework/cBPM-blockchain-system/network/
  #logPath
  logPackagePath: /home/steve/homework/cBPM-blockchain-system/backend/src/main/logs/