spring:
  profiles:
    active: dev

  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

logging:
  file:
    name: logs/cbpm.log
  level:
    root: warn
    org.springframework.security: warn
    org.springframework.web: warn
    com.cbpm.backend: info

network:
  orgNames: manufacturer, carrier, supplier, middleman
  orgMSPs: ManufacturerMSP, CarrierMSP, SupplierMSP, MiddlemanMSP
  orgAdminNames: manufacturer-admin, carrier-admin, supplier-admin, middleman-admin
  certificatePathSuffix: /admin/msp/signcerts/cert.pem
  privateKeyPathSuffix: /admin/msp/keystore/private_sk
