server:
  port: 8080
#windows环境
spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://172.19.241.74:3306/blockChain
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

backend:
  # 网络配置文件路径
  networkConfigPath: src/main/resources/connection2.json
  #network path
  networkPath: ../network/
  #logPath
  logPackagePath: src/main/logs/
